# Generated by Django 5.2.11 on 2026-03-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user_profile', '0003_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
    ]
