# Generated by Django 5.2.11 on 2026-03-17 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_profile'),
        ('user_profile', '0003_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='pin',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6 digit PIN code')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='user_profile.profile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
