# Generated by Django 5.2.11 on 2026-03-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_city_alter_location_country_and_more'),
        ('user_profile', '0003_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='user_profile.profile'),
        ),
    ]
