# Generated by Django 5.2.11 on 2026-03-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='profile',
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('car', 'Car')], max_length=20),
        ),
    ]
