# Generated by Django 5.2.11 on 2026-02-06 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Maruti Suzuki', 'Maruti Suzuki'), ('Hyundai', 'Hyundai'), ('Tata Motors', 'Tata Motors'), ('Mahindra', 'Mahindra'), ('Toyota', 'Toyota'), ('Kia', 'Kia'), ('Volkswagen', 'Volkswagen'), ('Honda', 'Honda'), ('Skoda', 'Skoda'), ('MG Motor', 'MG Motor')], max_length=50)),
                ('car_model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)])),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=20)),
                ('kilometers', models.CharField(choices=[('Up to 10,000 km', 'Up to 10,000 km'), ('10,000 - 20,000 km', '10,000 - 20,000 km'), ('20,000 - 30,000 km', '20,000 - 30,000 km'), ('30,000 - 40,000 km', '30,000 - 40,000 km'), ('40,000 - 50,000 km', '40,000 - 50,000 km'), ('50,000 - 60,000 km', '50,000 - 60,000 km'), ('60,000 - 70,000 km', '60,000 - 70,000 km'), ('70,000 - 80,000 km', '70,000 - 80,000 km'), ('80,000 - 90,000 km', '80,000 - 90,000 km'), ('90,000 - 1,00,000 km', '90,000 - 1,00,000 km'), ('1,00,000 - 1,50,000 km', '1,00,000 - 1,50,000 km'), ('1,50,000 - 2,00,000 km', '1,50,000 - 2,00,000 km'), ('Above 2,00,000 km', 'Above 2,00,000 km')], max_length=50)),
                ('reg_state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('car_location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
