# Generated by Django 5.2.11 on 2026-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='img_type',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side'), ('interior', 'Interior'), ('engine', 'Engine')], max_length=50),
        ),
    ]
