# Generated by Django 5.2.11 on 2026-03-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_imagestore_img_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagestore',
            old_name='image',
            new_name='car_image',
        ),
        migrations.AddField(
            model_name='cardetail',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetail',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='img_type',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side'), ('interior', 'Interior'), ('engine', 'Engine')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='imagestore',
            constraint=models.UniqueConstraint(fields=('car', 'img_type'), name='unique_car-image_type'),
        ),
    ]
