# Generated by Django 5.2.11 on 2026-03-18 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_profile'),
        ('seller', '0003_rename_image_imagestore_car_image_cardetail_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetail',
            name='car_location',
        ),
        migrations.RemoveField(
            model_name='cardetail',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cardetail',
            name='longitude',
        ),
        migrations.AddField(
            model_name='cardetail',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
