# Generated by Django 5.2.11 on 2026-03-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_location_profile_location_location_type'),
        ('seller', '0004_remove_cardetail_car_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetail',
            name='location',
        ),
        migrations.AddField(
            model_name='cardetail',
            name='car_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='location.location'),
        ),
    ]
