# Generated by Django 5.2.11 on 2026-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_cardetail_location_cardetail_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
