# Generated by Django 5.2.11 on 2026-03-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_cardetail_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
