# Generated by Django 5.2.11 on 2026-03-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetotp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
