# Generated by Django 5.2.11 on 2026-03-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_delete_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
