# Generated by Django 5.2.11 on 2026-03-18 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10 digit PIN code')]),
        ),
    ]
