# Generated by Django 5.2.11 on 2026-03-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_profile_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
