# Generated by Django 5.2.11 on 2026-03-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
